include:
    - docker-compose.local.yaml
services:
#  ftgo-business-service:
#      build:
#          context: ../
#          dockerfile: service-business.Dockerfile
#      environment:
#          SPRING_PROFILES_ACTIVE: dev
#          SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/business_db
#          SPRING_DATASOURCE_USERNAME: postgres
#          SPRING_DATASOURCE_PASSWORD: postgres
#      depends_on:
#          - postgres
#      ports:
#          - "8080:8080"
#      command: ["./wait-for-it.sh", "postgres:5432", "--", "java", "-jar", "/app.jar"]
#      volumes:
#        - ./wait-for-it.sh:/wait-for-it.sh