server:
  port: 8080
  shutdown: graceful

spring:
  profiles:
    active: local
  main:
    banner-mode: "off"
  application:
    name: customer-profile-svc
  datasource:
    url: jdbc:postgresql://localhost:5432/customer_profile_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    default-property-inclusion: non_null

management:
  server:
    port: 8081
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: db
  endpoints:
    web:
      base-path: "/"
      exposure:
        include: prometheus,health
