server:
  port: 8080
  shutdown: graceful

spring:
  profiles:
    active: local
  main:
    banner-mode: "off"
  application:
    name: fu-business-service
  datasource:
    write:
      pool-name: write-pool
      maximum-pool-size: 3
      connection-timeout: 1000
      continue-on-error: "true"
      initialization-fail-timeout: -1
    read:
      pool-name: read-pool
      maximum-pool-size: 3
      connection-timeout: 1000
      read-only: true
      continue-on-error: "true"
      initialization-fail-timeout: -1
    jdbc:
      initialize-schema: never
    job-store-type: jdbc

#management:
#  server:
#    port: 8081
#  endpoint:
#    health:
#      show-details: always
#      probes:
#        enabled: true
#      group:
#        readiness:
#          include: db,kafka
#  endpoints:
#    web:
#      base-path: "/"
#      exposure:
#        include: prometheus,health
