[versions]
kotlin = "2.1.20"
ktlint = "11.6.1"
test-logger = "3.2.0"

[libraries]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
test-logger = { id = "com.adarshr.test-logger", version.ref = "test-logger" }
