spring:
  datasource:
    write:
      jdbc-url: jdbc:postgresql://localhost:5432/merchant_profile_db
      username: postgres
      password: postgres
    read:
      jdbc-url: jdbc:postgresql://localhost:5432/merchant_profile_db
      username: postgres
      password: postgres
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-root.xml
    url: jdbc:postgresql://localhost:5432/merchant_profile_db
    user: postgres
    password: postgres